# Generated by Django 2.2.3 on 2020-01-16 05:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioContatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuadagnoEffettivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provenienza', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Protocollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(blank=True, max_length=10)),
                ('data_registrazione', models.DateField()),
                ('indirizzo', models.CharField(max_length=30)),
                ('pratica', models.CharField(max_length=30)),
                ('parcella', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_scadenza', models.DateField(default=None)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-identificativo'],
            },
        ),
        migrations.CreateModel(
            name='RubricaClienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=50)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubricaReferenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=50)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('percentuale', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SpesaGestione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('causale', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('fattura', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('provenienza', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SpesaCommessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('provenienza', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
                ('protocollo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spesecommessa', to='Contabilita.Protocollo')),
            ],
        ),
        migrations.CreateModel(
            name='Ricavo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('movimento', models.CharField(choices=[('ACCONTO', 'ACCONTO'), ('SALDO', 'SALDO')], default='ACCONTO', max_length=15)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fattura', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('destinazione', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
                ('intestatario_fattura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sociofatturaricavo', to='Contabilita.Socio')),
                ('protocollo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ricavi', to='Contabilita.Protocollo')),
            ],
        ),
        migrations.AddField(
            model_name='protocollo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilita.RubricaClienti'),
        ),
        migrations.AddField(
            model_name='protocollo',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contabilita.RubricaReferenti'),
        ),
        migrations.AddField(
            model_name='protocollo',
            name='responsabile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contabilita.Socio'),
        ),
        migrations.CreateModel(
            name='Consulenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('richiedente', models.CharField(blank=True, max_length=40, null=True)),
                ('indirizzo', models.CharField(max_length=30)),
                ('attivita', models.CharField(max_length=40)),
                ('compenso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_scadenza', models.DateField(default=None)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contabilita.Socio')),
            ],
        ),
    ]
