# Generated by Django 3.2.25 on 2025-07-30 09:41

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioContatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('fatture', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Consulenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('richiedente', models.CharField(blank=True, max_length=40, null=True)),
                ('indirizzo', models.CharField(max_length=100)),
                ('attivita', models.CharField(max_length=40)),
                ('compenso', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_scadenza', models.DateField(default=None)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField(default=None)),
                ('identificativo', models.CharField(max_length=50, unique=True)),
                ('ente', models.CharField(choices=[('AdE', 'AdE'), ('INARCASSA', 'INARCASSA')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=10)),
                ('data_registrazione', models.DateField()),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-identificativo'],
            },
        ),
        migrations.CreateModel(
            name='Protocollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(blank=True, max_length=10)),
                ('data_registrazione', models.DateField()),
                ('indirizzo', models.CharField(max_length=100)),
                ('pratica', models.CharField(max_length=30)),
                ('parcella', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_scadenza', models.DateField(default=None)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-identificativo'],
            },
        ),
        migrations.CreateModel(
            name='RubricaClienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=50)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubricaReferenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=50)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpesaGestione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=50)),
                ('data_registrazione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('causale', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('fattura', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('provenienza', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
                ('f24', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spesagestione', to='Contabilita.f24')),
            ],
        ),
        migrations.CreateModel(
            name='SpesaCommessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('provenienza', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
                ('protocollo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spesecommessa', to='Contabilita.protocollo')),
            ],
        ),
        migrations.CreateModel(
            name='Ricavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('movimento', models.CharField(choices=[('ACCONTO', 'ACCONTO'), ('SALDO', 'SALDO')], default='ACCONTO', max_length=15)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('destinazione', models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='DEPOSITO', max_length=15)),
                ('fattura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricavi_fattura', to='Contabilita.fattura')),
                ('protocollo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricavi', to='Contabilita.protocollo')),
            ],
        ),
        migrations.AddField(
            model_name='protocollo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilita.rubricaclienti'),
        ),
        migrations.AddField(
            model_name='protocollo',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contabilita.rubricareferenti'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='protocollo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture', to='Contabilita.protocollo'),
        ),
        migrations.CreateModel(
            name='CodiceTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(choices=[(2050, '2050'), (2049, '2049'), (2048, '2048'), (2047, '2047'), (2046, '2046'), (2045, '2045'), (2044, '2044'), (2043, '2043'), (2042, '2042'), (2041, '2041'), (2040, '2040'), (2039, '2039'), (2038, '2038'), (2037, '2037'), (2036, '2036'), (2035, '2035'), (2034, '2034'), (2033, '2033'), (2032, '2032'), (2031, '2031'), (2030, '2030'), (2029, '2029'), (2028, '2028'), (2027, '2027'), (2026, '2026'), (2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984'), (1983, '1983'), (1982, '1982'), (1981, '1981'), (1980, '1980'), (1979, '1979'), (1978, '1978'), (1977, '1977'), (1976, '1976'), (1975, '1975'), (1974, '1974'), (1973, '1973'), (1972, '1972'), (1971, '1971'), (1970, '1970')])),
                ('mese', models.CharField(blank=True, choices=[('Gennaio', 'Gennaio'), ('Febbraio', 'Febbraio'), ('Marzo', 'Marzo'), ('Aprile', 'Aprile'), ('Maggio', 'Maggio'), ('Giugno', 'Giugno'), ('Luglio', 'Luglio'), ('Agosto', 'Agosto'), ('Settembre', 'Settembre'), ('Ottobre', 'Ottobre'), ('Novembre', 'Novembre'), ('Dicembre', 'Dicembre')], max_length=10, null=True)),
                ('identificativo', models.CharField(max_length=50)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('f24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codicetributo', to='Contabilita.f24')),
            ],
        ),
    ]
