# Generated by Django 2.1.3 on 2019-04-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guadagno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('movimento', models.CharField(choices=[('ACCONTO', 'ACCONTO'), ('SALDO', 'SALDO')], default='A', max_length=10)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fattura', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Protocollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=25)),
                ('referente', models.CharField(max_length=25)),
                ('mail_cliente', models.EmailField(max_length=40)),
                ('tel_cliente', models.CharField(max_length=20)),
                ('indirizzo', models.CharField(max_length=40)),
                ('parcella', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pratica', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RicavoEffettivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('percentuale', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SpesaCommessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('protocollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spesecommessa', to='Contabilita.Protocollo')),
            ],
        ),
        migrations.CreateModel(
            name='SpesaGestione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fattura', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('causale', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='guadagno',
            name='protocollo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guadagni', to='Contabilita.Protocollo'),
        ),
    ]
