# Generated by Django 3.2.25 on 2025-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spesagestione',
            name='identificativo',
        ),
        migrations.AddField(
            model_name='fattura',
            name='intestatario',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='spesagestione',
            name='provenienza',
            field=models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='CARTA', max_length=15),
        ),
    ]
