# Generated by Django 2.1.3 on 2019-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocollo',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
