# Generated by Django 2.1.3 on 2019-04-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0002_protocollo_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocollo',
            name='selected',
        ),
    ]
