# Generated by Django 3.2.25 on 2025-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0002_auto_20250806_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesacommessa',
            name='provenienza',
            field=models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='CARTA', max_length=15),
        ),
    ]
