# Generated by Django 3.2.25 on 2025-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0003_alter_spesacommessa_provenienza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulenza',
            name='richiedente',
            field=models.CharField(default='', max_length=40),
        ),
    ]
