# Generated by Django 2.1.3 on 2019-04-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0004_protocollo_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocollo',
            name='select',
        ),
    ]
