# Generated by Django 3.2.25 on 2025-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0004_alter_consulenza_richiedente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaclienti',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rubricareferenti',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
