# Generated by Django 3.2.25 on 2025-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0005_auto_20250809_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricavo',
            name='destinazione',
            field=models.CharField(choices=[('DEPOSITO', 'DEPOSITO'), ('CARTA', 'CARTA')], default='CARTA', max_length=15),
        ),
    ]
