# Generated by Django 2.1.3 on 2019-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0006_protocollo_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='select',
            field=models.NullBooleanField(default=False),
        ),
    ]
