# Generated by Django 3.2.25 on 2025-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0007_spesagestione_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spesacommessa',
            name='note',
        ),
        migrations.AddField(
            model_name='spesacommessa',
            name='causale',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
