# Generated by Django 2.1.3 on 2019-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0007_auto_20190429_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
