# Generated by Django 2.1.3 on 2019-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0009_remove_protocollo_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='cliente',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='identificativo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='mail_cliente',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='parcella',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='pratica',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='referente',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='protocollo',
            name='tel_cliente',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
