# Generated by Django 2.1.3 on 2019-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0010_auto_20190503_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='parcella',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
