# Generated by Django 2.1.3 on 2019-05-03 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0011_auto_20190503_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
