# Generated by Django 2.1.3 on 2019-05-03 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0012_auto_20190503_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollo',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
