# Generated by Django 2.1.3 on 2019-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilita', '0015_auto_20190503_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocollo',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
